ESportsLeaderboardMVC/Models/ErrorViewModel.cs
using System;

namespace ESportsLeaderboardMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ESportsLeaderboardMVC/Models/Player.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ESportsLeaderboardMVC.Models
{
    public class Player
    {
        public int PlayerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Handle { get; set; }
        public int TotalSubscribers { get; set; }
        public int TotalViewers { get; set; }
        public TimeSpan TotalTimeViewed { get; set; }
        public TimeSpan TotalTimeStreamed { get; set; }
        public int CurrentRank { get; set; }
        public int HighestRank { get; set; }
    }
}

ESportsLeaderboardMVC/Models/StreamSession.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ESportsLeaderboardMVC.Models
{
    public class StreamSession
    {
        public int SessionID { get; set; }
        public int PlayerID { get; set; }
        public DateTime SessionDate { get; set; }
        public int CurrentViewerCount { get; set; }
        public int TotalSessionViews { get; set; }
        public TimeSpan SessionTime { get; set; }
        public TimeSpan SessionTotalTimeViewed { get; set; }

    }
}

ESportsLeaderboardMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ESportsLeaderboardMVC.Models;

namespace ESportsLeaderboardMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ESportsLeaderboardMVC/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ESportsLeaderboardMVC.Models;
using ESportsLeaderboardMVC.Repositories.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ESportsLeaderboardMVC.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class PlayerController : ControllerBase
    {
        private readonly IPlayerRepository _playerRepo;

        public PlayerController(IPlayerRepository playerRepo)
        {
            _playerRepo = playerRepo;
        }

        public async Task<ActionResult<List<Player>>> Index()
        {
            // Retreives an unsorted list of players from the repo
            var playerList = await _playerRepo.GetListOfPLayersAsync();

            // The player list will be sorted in decending order based on the total number of subscribers
            playerList.Sort((a,b) => -1* a.TotalSubscribers.CompareTo(b.TotalSubscribers));

            // Loop through each player in the playerList
            for (int i = 0; i < playerList.Count(); i++)
            {
                // Assigns a currnet ranking for each player. Ranked from 1 to infinity for each player in the list.
                // Players at the front of the list are given the "top" rank of 1 onward. 
                playerList[i].CurrentRank = i+1;

                // HighestRank is intended to keep record of the highest ranking a player has acheived. 
                // If their current rank is higher than their previous rank, Highest rank is replaced with the current rank
                if (playerList[i].HighestRank <= playerList[i].CurrentRank)
                {
                    playerList[i].HighestRank = playerList[i].CurrentRank;
                }
            }
            return playerList;
        }
    }
}

ESportsLeaderboardMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ESportsLeaderboardMVC/Views/Player/Index.cshtml
@model IEnumerable<ESportsLeaderboardMVC.Models.Player>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PlayerID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Handle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalSubscribers)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalViewers)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalTimeViewed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalTimeStreamed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrentRank)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HighestRank)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PlayerID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Handle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalSubscribers)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalViewers)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalTimeViewed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalTimeStreamed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurrentRank)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HighestRank)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { id=item.PlayerID }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

ESportsLeaderboardMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ESportsLeaderboardMVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ESportsLeaderboardMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Index">View Players</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ESportsLeaderboardMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>